version: '3.9'
services:
  app:
    container_name: hyperf-template_app
    image: hyperf-template
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    build:
      context: ./
    environment:
      - DB_HOST=hyperf-template_mysql
      - DB_DATABASE=hyperf-template
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./:/opt/www
    ports:
     - 9503:9503
    depends_on:
      - mysql
      # - redis
    networks:
      - kong-net

  mysql:
    container_name: hyperf-template_mysql
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: hyperf-template
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - kong-net

  # redis:
  #   container_name: hyperf-template_redis
  #   image: redis:alpine
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   networks:
  #     - kong-net

volumes:
  mysql_db:

networks:
  kong-net:
    external: true  